- src/main/java/tr/edu/ogu/ceng/controller/InternshipRegistryController.java
- src/main/java/tr/edu/ogu/ceng/dto/InternshipRegistryDto.java
- src/main/java/tr/edu/ogu/ceng/model/InternshipRegistry.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
Update operations for Internship Registry clearly added.
> Internship Registry Update Endpoint Added

- src/main/java/tr/edu/ogu/ceng/controller/InternshipController.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
Internship delete operation is added.
> Internship delete operation is added.

- src/main/java/tr/edu/ogu/ceng/dto/StudentDto.java
> StudentDto Add

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/model/Student.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> Student Update

- src/main/java/tr/edu/ogu/ceng/controller/FacultyController.java
- src/main/java/tr/edu/ogu/ceng/service/FacultyService.java
Added deleteFaculty and getFaculties operations
> Added  deleteFaculty and getFaculties

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
Getirme fonksiyonu güncellendi.
> ID ile ogrenci getir.

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/controller/UserController.java
- src/main/java/tr/edu/ogu/ceng/dao/InternshipRegistryRepository.java
- src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
- src/main/java/tr/edu/ogu/ceng/model/InternshipDocument.java
- src/main/java/tr/edu/ogu/ceng/model/InternshipRegistry.java
- src/main/java/tr/edu/ogu/ceng/model/Setting.java
- src/main/java/tr/edu/ogu/ceng/model/Student.java
- src/main/java/tr/edu/ogu/ceng/model/User.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
- src/main/java/tr/edu/ogu/ceng/service/UserService.java
Modeller ve ilişkileri düzenlendi.
User ve Student arasındaki OneToOne ilişkisi için düzenlemeler yapıldı. Not : Şuanki versiyonda Student silindiğinde Student'a ait User da siliniyor. User silindiğinde Student'ın kalabilmesi için veri tabanında Delete Action Set Null uygulanması gerekiyor (istenen tasarım bu ise).
> Modeller veri tabanına uygun biçimde düzenlendi.

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
Student Controller sınıfında ResponseEntity classının olmaması projeyi compile ederken hata döndürüyordu. Gerekli kütüphane eklenildi.
> Fixed compilation error: Added required library

- src/main/java/tr/edu/ogu/ceng/controller/CompanyController.java
- src/main/java/tr/edu/ogu/ceng/controller/FacultyController.java
- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
- src/main/java/tr/edu/ogu/ceng/service/FacultyService.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
CompanyController'da tüm şirketlerin ve fakültelerin sayfalı olarak getirilmesini destekleyen bir sayfalama özelliği eklendi. getAllCompanies() adında yeni bir metod eklenerek pageNo, limit ve sortBy parametreleri ile şirket verilerinin sayfalı olarak alınmasına olanak sağlandı. FacultyController'daki getFaculties() metodu sayfalama yapması için PageableUtil sınıfını kullanacak şekilde güncellendi.
> Added pagination for retrieving all companies and faculties.

- src/main/java/tr/edu/ogu/ceng/controller/CompanyController.java
- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
Added pagination for retrieving students,
fixed deleteStudent method name,
fixed updateStudent method,
added delete company method
> Added pagination for Students

- src/main/java/tr/edu/ogu/ceng/service/Exception/DataAccessException.java
- src/main/java/tr/edu/ogu/ceng/service/Exception/NotAuthorizedException.java
- src/main/java/tr/edu/ogu/ceng/service/Exception/NotEnoughDiscSpaceException.java
- src/main/java/tr/edu/ogu/ceng/service/Exception/SQLException.java
- src/main/java/tr/edu/ogu/ceng/service/Exception/ServiceUnavailableException.java
İsterler dahil ileride oluşabilecek runtime hatalarını düşünerek fırlatılacak exceptionlar arttırıldı.
> Exception paketi farklı exceptionlarla genişletildi

- src/main/java/tr/edu/ogu/ceng/controller/UserController.java
- src/main/java/tr/edu/ogu/ceng/service/UserService.java
UserController'da tüm kullanıcıları getiren kod sayfalama özelliğine uyarlandı.
> Added pagination for retrieving all users

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
project should compile without problems. Will add other middleware later.
> added pageable find students by name

- pom.xml
- src/main/java/tr/edu/ogu/ceng/controller/InternshipController.java
- src/main/java/tr/edu/ogu/ceng/dto/InternshipDto.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
Internship Update controller gets and returns InternshipDto. Mapper used in InternshipService
> InternshipDto used in Internship Update

- src/main/java/tr/edu/ogu/ceng/model/Student.java
- src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
Student classının ekleme özelliği test edildi ve testin geçtiği gözlemlendi.
> Student add test

- src/main/java/tr/edu/ogu/ceng/controller/CompanyController.java
- src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> addCompany Function

- src/main/java/tr/edu/ogu/ceng/model/Company.java
- src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
- src/test/java/tr/edu/ogu/ceng/service/CompanyTest.java
- src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
add özelliği test edildi
student test üzerinde düzenleme yapıldı
CompanyService dosyasına AllArgsConstructor eklendi.
> Company add function test

- src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
Değişkenlerin kontrol edilmesi düzenlendi
> StudentAddTest fix

- src/main/java/tr/edu/ogu/ceng/dto/InternshipRegistryDto.java
- src/main/java/tr/edu/ogu/ceng/dto/UserDto.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
- src/main/java/tr/edu/ogu/ceng/service/UserTypeService.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
- src/test/java/tr/edu/ogu/ceng/service/UserTest.java
DToların sonradan eklenmesinden kaynaklı olarak maindeki compile hatası düzeltildi.
Bu commiti mainin sorunsuz compile edilebilmesi için atıyoruz. Testlerin yeni DTO lar sebebiyle fail olmasını ayrı bir pr üzerinden düzenleyeceğiz.
> Test compile hataları düzeltildi

- src/main/java/tr/edu/ogu/ceng/controller/InternshipController.java
- src/main/java/tr/edu/ogu/ceng/dto/InternshipDto.java
- src/main/java/tr/edu/ogu/ceng/dto/InternshipRegistryDto.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
InternshipDto and InternshipRegistryDTO files fixed and necessary functions are arranged to return DTO's.
> Internship classes edit and InternshipRegistry fix

- src/main/java/tr/edu/ogu/ceng/service/SettingService.java
Autowired anotasyonu eklenmiş ancak import edilmediği için compiler hatası oluyor.
> Compiler bug fix

- src/main/java/tr/edu/ogu/ceng/service/UserService.java
The saveUser method has been updated to check if the user's ID already exists
> The saveUser method has been updated

- src/main/java/tr/edu/ogu/ceng/model/Setting.java
- src/main/java/tr/edu/ogu/ceng/service/SettingService.java
Setting için Timestamp , LocalDateTime ile değiştirildi
> Timestamp replaced with LocalDateTime

- src/main/java/tr/edu/ogu/ceng/dto/InternshipDto.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
- src/test/java/tr/edu/ogu/ceng/service/FacultySupervisorTest.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
FacultySupervisorTest içerisindeki metodlar localDateTime türüne geçirilip compile hatası giderildi. Internshipservice içerisindeki compile hatası da düzeltildi. Güncel olarak uygulama compile oluyor
> Compile errors fixed

- src/main/java/tr/edu/ogu/ceng/controller/InternshipRegistryController.java
- src/main/java/tr/edu/ogu/ceng/dto/InternshipDto.java
- src/main/java/tr/edu/ogu/ceng/dto/InternshipRegistryDto.java
- src/main/java/tr/edu/ogu/ceng/model/Internship.java
- src/main/java/tr/edu/ogu/ceng/model/InternshipRegistry.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
> Internship and InternshipRegistry Dto files fixed

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
#27   Şu anda bir keyword ile isim, soyisim ve öğrenci numarasında eşleşen öğrencileri geri döndürüyor. İmplementasyonla ilgili birkaç sorum vardı hocam.
1. Keyword aynı anda hem rakam hem harf içeriyorsa error döndürmeli mi? İsimler rakam, öğrenci numaraları harf içeremiyor olarak düşünürsek.
2. Şu anda tek bir liste döndürüyor. Bunun yerine names_matched = [student1, student 2 ...], surnames_matched = [student1, student 2 ...], studentNos_matched = [student1, student 2 ...] gibi üç array mi döndürmeli?  Bu özellik sonradan eklenebilir.
3. Endpoint route ismi olarak "getByNameSurnameStudentNo" fazla mı uzun?
> Added search student endpoint

- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
arada bazı import statementlar silinmiş. Sorun düzeltildi.
> internship service hotfix

- src/main/java/tr/edu/ogu/ceng/enums/UserTypeEnum.java
- src/main/java/tr/edu/ogu/ceng/service/FacultyService.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
- src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
StudentDto içinde FacultyDto olarak değişen kısım ile ilgili gerekli düzenlemeler yapıldı. Enumda unutulan ADMIN eklendi. Geliştirmelerden sonra çalışmayan kısımlar düzeltildi.
> Değişen şartlara göre gerekli değişiklikler yapıldı

- src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
Fakülte sorumlusu güncelleme işleminden sonra createDate alanının null olması sorunu giderildi.
> Fakülte sorumlusu güncelleme fixed

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
searchStudent endpoint'i response olarak StudentResponseDto kullanması için değiştirildi. Service metodunun ismi endpoint metodları ile aynı yapıldı.
> searchStudent StudentResponseDto kullanmasi için güncellendi

- src/main/java/tr/edu/ogu/ceng/controller/InternshipRegistryController.java
- src/main/java/tr/edu/ogu/ceng/dto/requests/InternshipRegistryRequestDto.java
- src/main/java/tr/edu/ogu/ceng/dto/responses/InternshipRegistryResponseDto.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
- InternshipRegistry Request-Response Dto Formatına Dönüştürüldü
- getInternshipRegistry endpointi eklendi.
> InternshipRegistry Request-Response Dto Formatına Dönüştürüldü #173

- src/main/java/tr/edu/ogu/ceng/controller/FacultyController.java
- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/dto/requests/FacultyRequestDto.java
- src/main/java/tr/edu/ogu/ceng/dto/requests/StudentRequestDto.java
- src/main/java/tr/edu/ogu/ceng/dto/responses/StudentResponseDto.java
- src/main/java/tr/edu/ogu/ceng/service/FacultyService.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
- src/test/java/tr/edu/ogu/ceng/service/FacultyTest.java
- src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
FacultyRequestDto eklendi.
Student update metodu güncellendi.
Faculty update metodu güncellendi.
Student ve Faculty metotları request response pattern'e göre  güncellendi.
> Updated student and faculty services

- src/main/java/tr/edu/ogu/ceng/controller/InternshipController.java
- src/main/java/tr/edu/ogu/ceng/dao/InternshipRepository.java
- src/main/java/tr/edu/ogu/ceng/dto/responses/InternshipResponseDto.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
List internships by student id endpoint added.
> List Internships by Student Id

- src/main/java/tr/edu/ogu/ceng/dto/InternshipDto.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
Internship test class'ında derleme hatası için bug fix
> Internship Test Bug Fix

- src/main/java/tr/edu/ogu/ceng/controller/FacultySupervisorController.java
- src/main/java/tr/edu/ogu/ceng/dto/requests/FacultyRequestDto.java
- src/main/java/tr/edu/ogu/ceng/dto/requests/FacultySupervisorRequestDto.java
- src/main/java/tr/edu/ogu/ceng/dto/requests/UserRequestDto.java
- src/main/java/tr/edu/ogu/ceng/dto/responses/FacultySupervisorResponseDto.java
- src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
- src/test/java/tr/edu/ogu/ceng/service/FacultySupervisorTest.java
Fakülte sorumlusu ekledikten sonra geri dönen değerler güncellendi. User ın password ve username i artık return edilmiyor derste tartışıldığı üzere.
> faculty supervisor add return values edited as response dto

- test-scripts/AddFaculty-post.rest
- test-scripts/AddStudent-Post.rest
- test-scripts/DeleteFaculty-post.rest
- test-scripts/GetAllStudent-Get.rest
- test-scripts/GetFaculties-get.rest
- test-scripts/GetIdStudent-Get.rest
- test-scripts/Student-delete.rest
- test-scripts/UpdateFaculty-put.rest
- test-scripts/UpdateStudent-put.rest
> Rest Test Scripts Group1

- clients/public/.env.production
- clients/public/html/index.html
- clients/public/src/App.tsx
- src/main/java/tr/edu/ogu/ceng/security/RoleBasedAuthenticationSuccessHandler.java
Kullanıcı giriş yaptıktan sonra ilgili olduğu sayfaya yonlendirmesi yapıldı.
> Login page created

- src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
- test-scripts/getStudentByUserId.rest
Mevcut metot istek gönderildiğinde öğrenci id sine göre getiriyordu ,kullanıcı id sine göre getirecek şekilde değiştirildi.
> GetStudentByUserId Rest Test Script added

- test-scripts/Company-Search.rest
- test-scripts/Company-getAll.rest
Rests added for companygetall and companysearch
> Rests added for companygetall and companysearch

- pom.xml
- src/main/java/tr/edu/ogu/ceng/service/ForgotPasswordService.java
@ezgiozdikyar 
guava CacheBuilder used.
> Forgot password token timeout fixed

- db-scripts/datagenerator/.gitignore
- db-scripts/datagenerator/data_pool.py
- db-scripts/datagenerator/generate_rows_company.py
- db-scripts/datagenerator/generate_rows_internship.py
- db-scripts/datagenerator/generate_rows_student.py
- db-scripts/datagenerator/main.py
- db-scripts/datagenerator/readme.txt
- db-scripts/datagenerator/settings.py
for companies, students and internships
> scripts to generate db data

- clients/faculty-supervisor/src/App.tsx
- clients/faculty-supervisor/src/components/InternshipDashboard.tsx
- clients/faculty-supervisor/src/index.css
- clients/student/package-lock.json
- clients/student/src/App.tsx
- clients/student/src/components/InternshipDashboard.tsx
- clients/student/src/index.css
Öğrenciler ve fakulte sorumlusu için için karşılama ekranı resimdeki gibi eklenmiştir.
> Added first screen for students and faculty-supervisor with css

- src/main/java/tr/edu/ogu/ceng/controller/FacultySupervisorController.java
- src/main/java/tr/edu/ogu/ceng/dao/FacultySupervisorRepository.java
- src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
Error fixed at facultySupervisor repository
> Error_fix at facultySupervisor

- clients/public/src/App.tsx
- clients/public/src/components/ResetPassword.tsx
- src/main/java/tr/edu/ogu/ceng/controller/ForgotPasswordController.java
> Şifre güncelleme ekranı oluşturuldu.

- clients/public/package.json
- clients/student/package-lock.json
- clients/student/package.json
- clients/student/src/App.tsx
- clients/student/src/components/AllInternships.tsx
- clients/student/src/components/InternshipDashboard.tsx
- clients/student/src/index.css
- clients/student/src/index.tsx
- clients/student/src/types/InternshipType.tsx
- clients/student/src/types/StudentType.tsx
- clients/student/tailwind.config.js
Stajlarım liste ekranı eklendi.
Route işlemleri eklendi.
Liste ekranında şirket ve fakülte sorumlusu kısımları güncellenecek.
Status renkleri düzenlenecek
> Stajlarım liste ekranı eklendi

- clients/student/package-lock.json
> bug-fix-package-lock.json

- db-scripts/imsdb7.sql
genel bir fonksiyon oluşturulup create_date ve update_date içeren tablolara trigger olarak eklendi
> create update dates trigger

- clients/company-supervisor/.env.production
- clients/company-supervisor/src/App.tsx
- clients/company-supervisor/src/components/InternshipRow.tsx
- clients/company-supervisor/src/components/StudentInfo.tsx
- clients/company-supervisor/src/types/StudentType.tsx
Öğrencinin ismine tıklayarak öğrenci bilgilerine erişilebilmekte.
> CompanySupervisor Öğrenci Bilgisi Görüntüleme Ekranı

- clients/company-supervisor/src/components/CompanyDashboard.tsx
Company-supervisor için grup2 nin çalışmaları doğrultusunda "card components" güncellendi.
> updated companysupervisor cards

- clients/company-supervisor/src/App.tsx
- clients/company-supervisor/src/components/InternshipRow.tsx
- clients/company-supervisor/src/components/StudentInfo.tsx
Student Info pop up'ına scroll bar eklendi ve düzenlendi. Stajlar sayfasındaki approved, pending, rejected durum renkleri ayarlandı.
> Company Supervisor geliştirildi.

- clients/student/src/App.tsx
- clients/student/src/components/AllInternships.tsx
- clients/student/src/components/CompanyInfo.tsx
- clients/student/src/components/InternshipDashboard.tsx
- clients/student/src/components/InternshipDocuments.tsx
- clients/student/src/types/DocumentType.tsx
The InternshipDocument Screen added, and the authentication has been removed. Additionally, some edits have been made to code.
**Staj Dokümanları Ekranı**
> InternshipDocument Screen

- clients/faculty-supervisor/src/components/AllInternships.tsx
- clients/faculty-supervisor/src/components/InternshipDocuments.tsx
- clients/faculty-supervisor/src/types/DocumentType.tsx
> Fakülte sorumlusuna ait stajlar ekranı için staj belgeleri pop up ekranı eklendi

- clients/faculty-supervisor/.env.development.local
- clients/faculty-supervisor/src/containers/CompanyListContainer/CompanyListContainer.css
routing inside facultysupervisor changed to work it normal,
Some changes on companylisting design to look better
> routing inside facultysupervisor changed, some changes on companylisting design

- clients/faculty-supervisor/src/components/Header.tsx
- clients/faculty-supervisor/src/components/InternshipCard.tsx
- clients/faculty-supervisor/src/components/InternshipDashboard.tsx
- clients/faculty-supervisor/src/index.css
- clients/student/src/components/Header.tsx
- clients/student/src/components/InternshipCard.tsx
- clients/student/src/components/InternshipDashboard.tsx
- clients/student/src/index.css
header kısmı güncellendi kartlara özellikler eklendi.
> updated header and cards

- clients/faculty-supervisor/src/components/Header.tsx
- clients/faculty-supervisor/src/components/InternshipDashboard.tsx
- clients/student/src/components/InternshipDashboard.tsx
fazladan yanlışlıkla sildiklerimi tekrar yükledim
> extra deleted ones re-uploaded

- clients/company-supervisor/src/App.tsx
- clients/company-supervisor/src/components/Footer.tsx
- clients/company-supervisor/src/components/Header.tsx
- clients/company-supervisor/src/components/PaginationButton.tsx
- clients/company-supervisor/src/routes/Company.tsx
- clients/company-supervisor/src/routes/Root.tsx
Company Supervisor ekranları için Internship listeleme ekranına sayfalama fonksiyonelliği eklendi. Küçük görsel hatalar giderildi.
> Company Supervisor ekranları için Internship listeleme ekranına sayfalama fonksiyonelliği eklendi. Küçük görsel hatalar giderildi.

- clients/student/src/components/InternshipDashboard.tsx
- db-scripts/imsdb8.sql
Frontend compile error fixed, 
db-script error fixed
> Derleme ve çalışma zamanı hataları giderildi.

- clients/company-supervisor/package-lock.json
- clients/company-supervisor/package.json
Added tailwind prettier plugin  for better formatted classes
> Added tailwind prettier plugin

- clients/public/html/index.html
- clients/public/package-lock.json
- clients/public/package.json
- clients/public/src/components/Login.tsx
sifre sifirlama butonuna basildiginda kullaniciya gerçekleşen islem bilgisi için spinner eklendi.
Konsolda çıkan integrity hatası giderildi.
> Spinner added for reset password button

- db-scripts/datagenerator/methods/Student.py
- db-scripts/datagenerator/readme.txt
düzenlenen students tablosuna göre sorgular güncellenmiştir
yeni veritabanı açmak istemiyorsanız
- main.py dosyasındaki ONLY_CLEAR değişkenini True olarak değiştirin (ONLY_CLEAR = True) ve çalıştırın
- veritabanınızda imsdb9.sql scriptini çalıştırın
- ONLY_CLEAR değişkenini False olarak değiştirin ve main.py ı çalıştırın
> 9. db scripti için data generator güncellemesi

- clients/faculty-supervisor/src/App.tsx
- clients/faculty-supervisor/src/components/AllInternships.tsx
- clients/faculty-supervisor/src/components/InternshipCard.tsx
- clients/faculty-supervisor/src/components/InternshipDashboard.tsx
- clients/faculty-supervisor/src/components/InternshipDocuments.tsx
- clients/faculty-supervisor/src/types/FacultySupervisorType.tsx
- clients/faculty-supervisor/src/types/InternshipType.tsx
- clients/faculty-supervisor/src/types/UserType.tsx
- src/main/java/tr/edu/ogu/ceng/controller/FacultySupervisorController.java
- src/main/java/tr/edu/ogu/ceng/dao/FacultySupervisorRepository.java
- src/main/java/tr/edu/ogu/ceng/dto/responses/InternshipResponseCompanyDto.java
- src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
Staj belgeleri indirme eklendi.
Kullanıcıya göre işlem yapma gerçekleştirildi.
Fakülte sorumlusu InternshipDashboard'daki yönlendirme hataları giderildi.
> Staj belgeleri indirme eklendi.

- clients/public/src/components/ResetPassword.tsx
- clients/public/src/index.css
- src/main/java/tr/edu/ogu/ceng/service/ForgotPasswordService.java
> Reset password page design updated.

- clients/student/html/index.html
- clients/student/src/App.tsx
- clients/student/src/components/Header.tsx
- clients/student/src/components/StudentProfile.tsx
- clients/student/src/types/StudentType.tsx
> Student profile page is created

- clients/public/package-lock.json
- clients/public/package.json
- clients/public/src/App.tsx
- clients/public/src/components/Companies.tsx
- clients/public/src/components/Header.tsx
- clients/public/src/components/Login.tsx
- clients/public/src/components/ResetPassword.tsx
- clients/public/src/index.css
- clients/public/src/style/company.css
- clients/public/src/types/CompanyType.tsx
- clients/public/tailwind.config.js
- src/main/java/tr/edu/ogu/ceng/controller/CompanyController.java
- src/main/java/tr/edu/ogu/ceng/service/WebSecurityConfig.java
Navbara Firmalar linki eklendi
Authorization gerektirmeyecek şekilde firmaları listeleyen ekran eklendi
> companies panel added

- clients/company-supervisor/src/components/InternshipDocument.tsx
- clients/company-supervisor/src/components/InternshipRow.tsx
- clients/company-supervisor/src/types/InternshipDocumentType.tsx
- db-scripts/datagenerator/methods/Internship.py
> Company supervisor view internship docs

- clients/company-supervisor/src/components/InternshipEvaluateForm.tsx
- clients/company-supervisor/src/components/InternshipRow.tsx
- clients/company-supervisor/src/routes/Company.tsx
- clients/company-supervisor/src/routes/Root.tsx
- clients/company-supervisor/src/types/InternshipEvalFromType.tsx
- src/main/java/tr/edu/ogu/ceng/controller/InternshipEvaluateFormController.java
- src/main/java/tr/edu/ogu/ceng/dao/InternshipEvaluateFormRepository.java
- src/main/java/tr/edu/ogu/ceng/dto/requests/InternshipEvaluateFormRequestDto.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipEvaluateFormService.java
Internship Evaluate Form ekranı oluşturuldu
gerekli api'lar tanımlandı
> CompanySupervisor Internship Evaluate Form ekranı

- clients/company-supervisor/src/components/InternshipDocument.tsx
- clients/company-supervisor/src/routes/Root.tsx
also fixed path for fetching internship documents
> Added search box for company supervisor

- clients/admin/src/components/AddFacultySupervisorModalForm.tsx
- clients/admin/src/components/AddModalForm.tsx
- clients/admin/src/components/CompanySupervisors.tsx
- clients/admin/src/components/FacultySupervisors.tsx
- clients/admin/src/components/StudentAddModalForm.tsx
- clients/admin/src/components/StudentUpdateModalForm.tsx
- clients/admin/src/components/Students.tsx
- clients/admin/src/components/UpdateFacultySupervisorModalForm.tsx
- clients/admin/src/components/UpdateModalForm.tsx
- clients/admin/src/index.css
Admin sayfasında öğrenci ekleme ve düzenleme modallarına validasyon eklendi.
> Admin sayfasında öğrenci ekleme ve düzenleme modalları

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
- src/main/java/tr/edu/ogu/ceng/model/Company.java
- src/main/java/tr/edu/ogu/ceng/model/CompanySupervisor.java
- src/main/java/tr/edu/ogu/ceng/model/Faculty.java
- src/main/java/tr/edu/ogu/ceng/model/Internship.java
- src/main/java/tr/edu/ogu/ceng/model/InternshipRegistry.java
- src/main/java/tr/edu/ogu/ceng/model/Language.java
- src/main/java/tr/edu/ogu/ceng/model/Student.java
- src/main/java/tr/edu/ogu/ceng/model/User.java
- src/main/java/tr/edu/ogu/ceng/service/StudentService.java
- src/test/java/tr/edu/ogu/ceng/service/CompanyTest.java
- src/test/java/tr/edu/ogu/ceng/service/FacultySupervisorTest.java
- src/test/java/tr/edu/ogu/ceng/service/FacultyTest.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
- src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
- src/test/java/tr/edu/ogu/ceng/service/UserTest.java
Builder kaldırıldı. Testler düzenlendi.
> Builder yapısının entitylerden kaldırılması

- src/main/java/tr/edu/ogu/ceng/controller/SettingController.java
Endpoint çalışıyor, client üzerinde yapılan değişiklikler aynı şekilde veritabanına yansıyor. 
SettingDto içindeki Key property'si kaldırılabilir (bunun için bir setting test oluşturulması gerekebilir). Şu anlık sorun olmaması adına SettingDto bu şekilde bırakıldı.
> Endpoint kontrol edildi, yorum eklendi.

- db-scripts/datagenerator/methods/Company.py
- db-scripts/datagenerator/methods/Faculty.py
- db-scripts/datagenerator/methods/Hash.py
- db-scripts/datagenerator/methods/Student.py
- db-scripts/datagenerator/methods/User.py
- db-scripts/datagenerator/readme.txt
Hash fonksiyonu eklendi (java dosyasında bcrypt round:10 olarak çeviriyordu aynı yaptım) Company, Faculty, Student python dosyalarındaki 123 kısmı hashlenmiş halleriyle değiştirildi. Readme'ye gereklilik olarak bcrypt kütüphanesi eklendi. Yusuf Hocamın sildiği ilk açılışta otomatik hashleme kısmı merge edildikten sonra işleme alınması rica olunur.
> Python scriptinin hashli şekilde dummydata doldurması için

- clients/company-supervisor/src/error-page.tsx
- clients/public/src/components/Header.tsx
- clients/student/src/components/Header.tsx
> Başlığa tıklanıp ana sayfaya gitme ayarlandı hepsinde

- clients/admin/src/components/Footer.tsx
- clients/company-supervisor/src/components/Footer.tsx
- clients/faculty-supervisor/src/components/Footer.tsx
- clients/public/src/components/Footer.tsx
- clients/student/src/components/Footer.tsx
> footer area changed

- clients/public/src/components/Login.tsx
- clients/public/src/index.css
> şifremi unuttum kısmındaki hata mesajının gösterilmesi güncellendi

- clients/admin/src/hooks/useSupervisorManagement.ts
- clients/admin/src/hooks/userFacultySupervisorManagement.ts
hata verdiği durumlar için frontendde başarıyla silindi mesajı veriyordu hata mesajına çevrildi. 
Hata sebebi: "ims_faculty_supervisors" violates foreign key constraint "ims_internships_faculty_supervisors_fk" on table "ims_internships" Ayrıntı: Key (id)=(30) is still referenced from table "ims_internships". yani ims_internships içinde foregin key olarak tanımlanıyor sildiğimiz fakülte sorumlusu.
> fakülte sorumlusu silinmesi çalışıyor.

- clients/faculty-supervisor/src/components/Header.tsx
- clients/faculty-supervisor/src/components/PaginationButton.tsx
- clients/faculty-supervisor/src/components/StudentList.tsx
- clients/faculty-supervisor/src/index.css
- clients/faculty-supervisor/src/modals/StudentAddModal/StudentAddModal.tsx
Faculty-supervisor için öğrenci listeleme sayfa görünümü belirlenen formata dönüştürüldü.
> 365-FacultySupervisor Öğrenci Listeleme Ekranı

- src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipEvaluateFormService.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
- src/main/java/tr/edu/ogu/ceng/service/SettingService.java
- src/test/java/tr/edu/ogu/ceng/service/CompanyTest.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
- src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
Log ve exception satırları yer değiştirildi, testlere MessageResource parametresi eklendi. Maven Install kısmında testler hata vermiyor, build alıyor.
> 412_Bugfix_HY

- db-scripts/datagenerator/methods/Company.py
- db-scripts/datagenerator/methods/Faculty.py
- db-scripts/datagenerator/methods/Student.py
- db-scripts/datagenerator/methods/User.py
> 389 dummydata email yaratma güncellendi

- src/main/java/tr/edu/ogu/ceng/controller/CompanySupervisorController.java
- src/main/java/tr/edu/ogu/ceng/dto/requests/CompanySupervisorAdminRequestDto.java
- src/main/java/tr/edu/ogu/ceng/service/CompanySupervisorService.java
Closes #348
Closes #349
CompanySupervisor ekleme işlemi için yeni endpoint eklendi frontend kısmı için yeni issue açılacaktır.
> CompanySupervisor checkAdd endpoint added

- clients/admin/src/components/Students.tsx
- clients/admin/src/index.css
Search input has been added, it works based on name number and TR ID.
> Add search input

- clients/company-supervisor/src/components/InternshipEvaluateForm.tsx
- clients/company-supervisor/src/components/InternshipRow.tsx
- clients/company-supervisor/src/index.css
- clients/company-supervisor/src/types/InternshipEvalFromType.tsx
Backend kısmı için sorular question{soru_numarası} adıyla kaydedildi, veriler 0,5 aralığında 0 en yüksek 5 en düşük olacak şekilde ayarlandı.
> Staj değerlendirme formu oluşturuldu, veriler database için hazırlandı. #378

- clients/faculty-supervisor/src/components/InternshipDocuments.tsx
- pom.xml
- src/main/java/tr/edu/ogu/ceng/controller/InternshipDocumentsController.java
- src/main/java/tr/edu/ogu/ceng/dao/InternshipDocumentsRepository.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipDocumentsService.java
Faculty-supervisor sayfasında listelenen staj bilgilerini pdf olarak indirebilme sağlandı.
> Staj bilgilerini pdf olarak indirme

- src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
Öğrenci bilgileri çekilirken id spring securityden çekildi
> Güvenlik açığının giderilmesi

- clients/faculty-supervisor/package-lock.json
- clients/faculty-supervisor/package.json
- Font Awesome kütüphanesi güncellendi: "@fortawesome/fontawesome-svg-core" sürümü "^1.3.0" olarak güncellendi.
- Material-UI kütüphanesi güncellendi: "@mui/material" sürümü "^5.3.0" olarak güncellendi.
- Axios kütüphanesi güncellendi: "axios" sürümü "^1.4.0" olarak güncellendi.
- http-proxy-middleware kütüphanesi güncellendi: "http-proxy-middleware" sürümü "^2.0.0" olarak güncellendi.
- React Hook Form kütüphanesi güncellendi: "react-hook-form" sürümü "^7.44.0" olarak güncellendi.
- React Router kütüphanesi güncellendi: "react-router-dom" sürümü "^6.13.0" olarak güncellendi.
- Yup kütüphanesi güncellendi: "yup" sürümü "^1.2.0" olarak güncellendi.
- Tailwind CSS kütüphanesi güncellendi: "tailwindcss" sürümü "^3.0.0" olarak güncellendi.
> faculty supervisor react upgrade

- clients/public/src/components/Companies.tsx
- src/main/java/tr/edu/ogu/ceng/controller/InternshipController.java
- src/main/java/tr/edu/ogu/ceng/dao/InternshipRepository.java
- src/main/java/tr/edu/ogu/ceng/security/WebSecurityConfig.java
- src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
Public modülünde firma listesinde her firmanın toplam kaç stajyer aldığı sayısı bir sütun olarak gösteriliyor.
> Firmaların stajyer sayılarının görüntülenebilmesi sağlandı

- clients/public/package-lock.json
- clients/public/package.json
- Font Awesome kütüphanesi güncellendi: "@fortawesome/fontawesome-svg-core", "@fortawesome/free-regular-svg-icons", "@fortawesome/free-solid-svg-icons" ve "@fortawesome/react-fontawesome" sürümleri "^6.4.0" olarak güncellendi.
- Axios kütüphanesi güncellendi: "axios" sürümü "^1.5.0" olarak güncellendi.
- Bootstrap kütüphanesi güncellendi: "bootstrap" sürümü "^5.3.2" olarak güncellendi.
- React Hook Form kütüphanesi güncellendi: "react-hook-form" sürümü "^7.44.0" olarak güncellendi.
- React Router kütüphanesi güncellendi: "react-router-dom" sürümü "^6.13.0" olarak güncellendi.
- Yup kütüphanesi güncellendi: "yup" sürümü "^1.2.0" olarak güncellendi.
- Tailwind CSS kütüphanesi güncellendi: "tailwindcss" sürümü "^3.0.0" olarak güncellendi.
> Public react sürümü güncellenmesi

- clients/public/src/components/Companies.tsx
- clients/public/src/style/company.css
- src/main/java/tr/edu/ogu/ceng/controller/CompanyController.java
> PUBLIC modülü: Firmalar sayfasında firma listesi sayfalı olarak gösterildi

- src/main/java/tr/edu/ogu/ceng/controller/FacultySupervisorController.java
- src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
- src/test/java/tr/edu/ogu/ceng/service/FacultySupervisorTest.java
FacultySupervisorService_Added and Moved model mappers in the FacultySupervisorService layer to the controller
> FacultySupervisorService_Added

- src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
Student servicedeki dosya işlemlerinin testleri ve deleteStudent testleri yazıldı
> Student servicedeki Testler

- src/test/java/tr/edu/ogu/ceng/service/FacultyTest.java
Test Coverage:
FacultyService -> getFaculties(Pageable pageable)
FacultyService ->countFaculties() 
Testler eklenmeden önce coverage:
Yazdığım test fonksiyonları:
Testler eklendikten sonra coverage:
> FacultyTest classında testi yazılmayan fonksiyonların testleri eklendi

- src/test/java/tr/edu/ogu/ceng/service/CompanySupervisorTest.java
CompanySupervisorService -> getById(Long id)
CompanySupervisorService -> delete(Long id)
CompanySupervisorService -> getUsersCompany()
> CompanySupervisorTest Added

- src/test/java/tr/edu/ogu/ceng/service/CompanySupervisorTest.java
> added 2 tests

- src/test/java/tr/edu/ogu/ceng/service/InternshipJournalTest.java
Test Coverage:
InternshipJournalsService->
getAllInternshipJournalsByInternshipId,
updateInternshipJournal
Test for getAllInternshipJournalsByInternshipId
Test for updateInternshipJournal and GetAllInternshipJournalsById_EmptyList
Coverage Report For InternshipJournalsService Before
Coverage Report For InternshipJournalsService After
> Test internship journals service heo

- src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
StudentService  -> countStudents
StudentService  -> getStudentByUserId testleri eklendi
> Student service testleri eklendi

- src/test/java/tr/edu/ogu/ceng/service/FacultyTest.java
FacultyService ->updateFaculty
Test öncesi
Test sonrası
> FacultyService Update Test

- src/test/java/tr/edu/ogu/ceng/service/CompanySupervisorTest.java
Yazdığım 2 method öncesi coverage:
Yazdıktan sonraki coverage:
> CompanySupervisorService 2 test eklendi

- src/test/java/tr/edu/ogu/ceng/service/UserTest.java
Test Coverage: UserService->getAllUsers
before:
after:
> GetAllUsers methodu test edildi.

- src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
InternshipEvaluateFormService -> getByInternshipId 
InternshipEvaluateFormService -> mapEntityToDto
InternshipEvaluateFormService -> saveInternshipEvalForm
Metodları için test fonksiyonları yazıldı.
> InternshipEvaluateFormService Test

- src/test/java/tr/edu/ogu/ceng/service/InternshipEvaluateFormTest.java
> Test func added

- src/test/java/tr/edu/ogu/ceng/service/InternshipDocumentsServiceTest.java
> InternshipDocumentService Test

- src/test/java/tr/edu/ogu/ceng/service/SettingServiceTest.java
Coverage değeri %0 dan % 100 e yükseltildi.
> TestSettingService added

- src/test/java/tr/edu/ogu/ceng/service/FacultyTest.java
deleteFaculty
getFacultyById
convertToDto
> Add 3 test facultyservice
